In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from collections import defaultdict

In [2]:
# Load dataset.
tracks = pd.read_csv('data/fma_metadata/tracks_processed_filled.csv')

columns2drop = ['Unnamed: 0', 'track_id', 'artist_id']

tracks.drop(columns2drop, inplace=True, axis=1)

tracks.shape

(106486, 40)

In [3]:
from sklearn.model_selection import train_test_split, cross_val_score 

In [4]:
class_name = 'Attribution-NonCommercial-ShareAlike 3.0 International'

attributes = [col for col in tracks.columns if col != class_name]

X = tracks[attributes].values
y = tracks[class_name]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)

In [5]:
from sklearn.feature_selection import SelectKBest

In [6]:
sel = SelectKBest(k=4)
X_train_sel = sel.fit_transform(X_train, y_train)
for i in sel.scores_:
    print(i)
    #perche i p-values sono 0.0 ??? 
X_train_sel 

134.30464596601445
5.000347875216237
981.9395608590971
86.78052533401663
302.17809981130443
325.5084294731786
61.537436437145054
261.6576417249907
0.8846638549683375
0.30121948905320267
29.469778215950132
155.95529212053057
0.14149868843951258
29.34249872294262
16.5712785598535
511.04657154429805
231.98926079670886
0.1369367764481466
19.64518317531348
329.6823862217513
19.024114767689916
2.6881127390246213
1498.2972180056345
117.55300912767254
28.714181383248473
451.920532783418
624.4358962734955
763.8031990843158
1561.818396867397
nan
792.1658964880887
39.42877636764875
196.46990630339363
260.42279479857706
1458.0780089932366
158.01140740987208
91.47526683614677
362.3033551514102
nan


C:\Users\user\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: UserWarning: Features [29 38] are constant.
  UserWarning)
C:\Users\user\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


array([[7.6610e+03, 2.0100e+03, 2.9000e+01, 2.0100e+03],
       [7.7640e+03, 2.0100e+03, 1.0000e+00, 2.0100e+03],
       [1.6520e+03, 2.0080e+03, 1.0000e+00, 2.0090e+03],
       ...,
       [3.2490e+03, 2.0090e+03, 1.0000e+00, 2.0090e+03],
       [3.3400e+03, 2.0090e+03, 1.0000e+00, 2.0090e+03],
       [1.3801e+04, 2.0160e+03, 1.0000e+00, 2.0130e+03]])

In [11]:
sel = SelectKBest(k=2)
X_train_sel = sel.fit_transform(X_train, y_train)
for i in sel.scores_:
    print(i)
    
X_train_sel     #mantiene  temperature e light

134.30464596601445
5.000347875216237
981.9395608590971
86.78052533401663
302.17809981130443
325.5084294731786
61.537436437145054
261.6576417249907
0.8846638549683375
0.30121948905320267
29.469778215950132
155.95529212053057
0.14149868843951258
29.34249872294262
16.5712785598535
511.04657154429805
231.98926079670886
0.1369367764481466
19.64518317531348
329.6823862217513
19.024114767689916
2.6881127390246213
1498.2972180056345
117.55300912767254
28.714181383248473
451.920532783418
624.4358962734955
763.8031990843158
1561.818396867397
nan
792.1658964880887
39.42877636764875
196.46990630339363
260.42279479857706
1458.0780089932366
158.01140740987208
91.47526683614677
362.3033551514102
nan


C:\Users\user\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: UserWarning: Features [29 38] are constant.
  UserWarning)
C:\Users\user\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


array([[2.010e+03, 2.900e+01],
       [2.010e+03, 1.000e+00],
       [2.008e+03, 1.000e+00],
       ...,
       [2.009e+03, 1.000e+00],
       [2.009e+03, 1.000e+00],
       [2.016e+03, 1.000e+00]])

In [12]:
X_train

array([[ 1.0000e+00,  0.0000e+00,  7.6610e+03, ...,  2.9000e+01,
         2.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  1.0000e+00,  7.7640e+03, ...,  9.0000e+00,
         2.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  1.6520e+03, ...,  2.7000e+01,
         2.0000e+00,  0.0000e+00],
       ...,
       [ 0.0000e+00,  0.0000e+00,  3.2490e+03, ...,  2.7000e+01,
         2.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  3.3400e+03, ...,  3.0000e+00,
         2.0000e+00,  0.0000e+00],
       [-1.0000e+00, -1.0000e+00,  1.3801e+04, ...,  1.9000e+01,
         1.0000e+00,  0.0000e+00]])

In [13]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106486 entries, 0 to 106485
Data columns (total 40 columns):
 #   Column                                                  Non-Null Count   Dtype  
---  ------                                                  --------------   -----  
 0   album_comments                                          106486 non-null  int64  
 1   album_favorites                                         106486 non-null  int64  
 2   album_id                                                106486 non-null  int64  
 3   album_listens                                           106486 non-null  int64  
 4   album_tracks                                            106486 non-null  int64  
 5   album_type                                              106486 non-null  int64  
 6   artist_comments                                         106486 non-null  int64  
 7   artist_favorites                                        106486 non-null  int64  
 8   artist_location         